#!/usr/bin/python3

import os
import sys
import boto3
import random
import string

from minimoto_constants import *

RANDOMWORD_LENGTH = 10


def randomword():
   return ''.join(random.choice(string.ascii_lowercase)
                  for i in range(RANDOMWORD_LENGTH))


def main():
    if len(sys.argv) < 4:
        print("Not enough arguments")
        exit(1)
    images_dir = os.path.normpath(sys.argv[1])
    s3_dirname = images_dir + "_" + randomword()
    input_bucket_name = sys.argv[2]
    output_bucket_name = sys.argv[3]
    wait_flag = False
    if len(sys.argv) == 5 and sys.argv[4] == "--wait":
        wait_flag = True

    print("Getting boto3 clients and resources")
    s3 = boto3.resource("s3", region_name="ap-southeast-2")
    sqs = boto3.resource("sqs", region_name="ap-southeast-2")

    print("Uploading images in {} to input bucket at {}".format(
          images_dir, s3_dirname))
    input_bucket = s3.Bucket(input_bucket_name)
    for image in os.listdir(images_dir):
        input_bucket.upload_file(os.path.join(images_dir, image),
                                 os.path.join(s3_dirname, image))

    print("Sending message to transcoding queue")
    queue = sqs.get_queue_by_name(QueueName=TRANSCODING_REQUESTS_QUEUE_NAME)
    queue.send_message(MessageBody=s3_dirname)

    if wait_flag:
        print("Waiting for transcoding to complete...")
        output_obj = s3.Object(output_bucket_name, s3_dirname + ".mp4")
        output_obj.wait_until_exists()
    print("You'll find the output in s3://{bucket_name}/{s3_dirname}.mp4"
          .format(bucket_name=output_bucket_name, s3_dirname=s3_dirname))


if __name__ == "__main__":
    main()

