#!/usr/bin/python3

'''
All the AWS resources (EC2 instances, SQS queue, S3 buckets, AMIs, security
groups, etc.) needed to run a solution will be created and initialised using a
minimoto_setup program. The usage of the program is as follows (with sample
output):
    $ ./minimoto_setup keyfile aws_access_key_id aws_secret_access_key
    minimoto_setup: mandatory output messages follow
    S3_BUCKET_INPUT=s3://au.edu.unsw.cs9243.input
    S3_BUCKET_OUTPUT=s3://au.edu.unsw.cs9243.output
    CLIENT_USER=ubuntu
    CLIENT_ADDR=ec2-52-63-140-157.ap-southeast-2.compute.amazonaws.com
    WATCHDOG_USER=ubuntu
    WATCHDOG_ADDR=ec2-52-62-39-219.ap-southeast-2.compute.amazonaws.com
    SERVICE_USER=ubuntu
    SERVICE_AMI=ami-fae5c999
    $

The command-line arguments are:

keyfile: the full path to a .pem key file that will be used to access instances
over ssh. The file name will consist of the key name with the .pem extension, so
you can extract the key name from the file name.
aws_access_key_id: the AWS access key ID that is used as AWS credentials.
aws_secret_access_key: the AWS secret access key that is used as AWS
credentials.

The setup program must:

- Create an SQS queue.
- Create two S3 buckets: one for input, one for output.
- Launch and configure an EC2 client instance from which minimoto_client can be
run. This instance must contain the minimoto_client program and anything else
required to run it (except the images used as input data).
- Launch and configure an EC2 watchdog instance from which minimoto_watchdog can
be run. This instance must contain the minimoto_watchdog program and anything
else required to run it. Note that this instance should not automatically run
the watchdog.
- Launch and configure an EC2 service instance which will regularly run the
transcoding service. This instance must contain everything required to run the
transcoding service, and be configured to run the transcoding service regularly.
- Create an AMI based on the EC2 service instance that the watchdog can use to
launch new EC2 service instances.
- Create and configure any other resources needed to run the client, watchdog,
and transcoding service.

Some further notes:

- All the EC2 instances must allow ssh access to them using the given keyfile.
- Use the ap-southeast-2 AWS region, i.e., create all resources and run all
instances in this region. Do not use other regions.
- Since the setup program must perform a lot of work, the program may take a
long time to run. However, if it takes more than 10 minutes, please note this
and explain the reasons in your DESIGN doc.

minimoto_setup will have to pass information on to minimoto_cleanup about what
resources were created. One way to do this is using a shared file (that
minimoto_setup writes to and minimoto_cleanup reads from).

The mandatory output messages are as follows:

S3_BUCKET_INPUT=... : the S3 URL of the input bucket
S3_BUCKET_OUTPUT=... : the S3 URL of the output bucket
CLIENT_USER=... : the user name used to log in to the client EC2 instance
CLIENT_ADDR=... : the address of the client EC2 instance
WATCHDOG_USER=... : the user name used to log in to the watchdog EC2 instance
WATCHDOG_ADDR=... : the address of the watchdog EC2 instance
SERVICE_USER=...: the user name used to log in to a service EC2 instance
SERVICE_AMI=...: the ID of the AMI used for service instances

The setup program may print out other messages regarding its progress, it is up
to you what those messages are.
'''
# TODO check failure
# TODO figure out what minimoto_cleanup neeeds to know and print to a file for minimoto_cleanup

import os
import sys
import boto3
import subprocess

# TODO before submit remove test
GROUP_PREFIX = "au.unsw.edu.au.cs9243.2017.group12.test1"
USER = "ubuntu"

def start_instance(filename, keyfile, userdata):
    keyname = os.path.basename(keyfile)
    kwargs = {
        "ImageId": "ami-96666ff5",
        "KeyName": keyname,
        "NetworkInterfaces": [{"AssociatePublicIpAddress": True}],
        "UserData": userdata # TODO install boto3
        # TODO security group should not be default (else ssh blocked)
    }

    new_instance = ec2.run_instances(**kwargs)
    new_instance.wait_until_running()
    new_instance_url = new_instance["Instances"][0]["PublicDnsName"]

    # Upload script
    ADD_PROGRAM_STR = "scp -i {} {} {user}@{}:/home/{user}"
    add_program_cmd = ADD_PROGRAM_STR.format(
        keyfile, filename, new_instance_url, user=USER).split()
    subprocess.run(add_client_program_cmd)

    return new_instance

def main():
    if len(sys.argv) < 4:
        print("Not enough arguments")
        exit(1)
    keyfile = sys.argv[1]
    aws_access_key_id = sys.argv[2]
    aws_secret_access_key = sys.argv[3]

    print("Setting keys and region")
    subprocess.run("aws configure set aws_access_key_id {}"
                   .format(aws_access_key_id).split())
    subprocess.run("aws configure set aws_secret_access_key {}"
                   .format(aws_secret_access_key).split())
    subprocess.run("aws configure set region ap-southeast-2".split())

    print("Get boto3 clients")
    sqs = boto3.client("sqs")
    s3 = boto3.client("s3")
    ec2 = boto3.client("ec2")

    print("Creating SQS queue")
    queue_name = GROUP_PREFIX + ".queue"
    try:
        queue = sqs.create_queue(QueueName=queue_name)
    except:
        print("Queue name is not unique")
        exit(1)

    print("Creating input S3 bucket")
    input_bucket_name = GROUP_PREFIX + ".input"
    input_bucket_url = "s3://" + input_bucket_name + "/"
    input_bucket = s3.Bucket(input_bucket_name)

    print("Creating output S3 bucket")
    output_bucket_name = GROUP_PREFIX + ".output"
    output_bucket_url = "s3://" + output_bucket_name + "/"
    output_bucket = s3.Bucket(output_bucket_name)

    print("Starting EC2 client instance")
    client_ec2 = start_instance("minimoto_client", keyfile,
                                # TODO default setup boto3
                                "file://default_setup")
    client_url = client_ec2["Instances"][0]["PublicDnsName"]

    print("Starting EC2 watchdog instance")
    watchdog_ec2 = start_instance("minimoto_watchdog", keyfile,
                                  "file://default_setup")
    watchdog_url = watchdog_ec2["Instances"][0]["PublicDnsName"]

    print("Starting EC2 service instance")
    service_ec2 = start_instance("minimoto_service", keyfile,
                                 "file://minimoto_service_setup")

    print("Creating AMI from EC2 service instance for watchdog")
    service_ami_name = GROUP_PREFIX + ".service.ami"
    service_ami = service_ec2.create_image(Name=service_ami_name)

    print("minimoto_setup: mandatory output messages follow:")
    print("S3_BUCKET_INPUT={}".format(input_bucket_url))    # the S3 URL of the input bucket
    print("S3_BUCKET_OUTPUT={}".format(output_bucket_url))  # the S3 URL of the output bucket
    print("CLIENT_USER={}".format(USER))                    # the user name used to log in to the client EC2 instance
    print("CLIENT_ADDR={}".format(client_url))              # the address of the client EC2 instance
    print("WATCHDOG_USER={}".format(USER))                  # the user name used to log in to the watchdog EC2 instance
    print("WATCHDOG_ADDR={}".format(watchdog_url))          # the address of the watchdog EC2 instance
    print("SERVICE_USER={}".format(USER))                   # the user name used to log in to a service EC2 instance
    print("SERVICE_AMI={}".format(service_ami_name))        # the ID of the AMI used for service instances

if __name__ == "__main__":
    main()

