#!/usr/bin/python3

"""
The transcoding service layer is a pool of AWS EC2 instances, which we call
service instances. Each service instance is launched from the same Amazon
Machine Image (AMI), which you will have created as part of setup and which
contains the image-to-video transcoding code you will have implemented.

A transcoding process is launched by cron and must do the following.

- If the instance is still processing the previous request, do nothing and exit.
- Pull a request from an SQS queue. If no request is found, do nothing and exit.
- Download all images from the S3 bucket specified in the request (e.g.,
au.edu.unsw.cs9243.input/sample_images_xyz).
- Convert a series of images to an MP4 video using avconv (it is up to you how
you order the images, but ordering based on filename would be sufficient).
- Upload the MP4 video to the S3 bucket specified in the request
(e.g., au.edu.unsw.cs9243.output).
- It is important to limit the number of requests processed on a machine at one
time. Media transcoding is a CPU intensive task and processing multiple requests
on one machine poses a risk of a machine crash. This is why we start the jobs
via cron and make sure that only one is running at a time. Also, parallelisation
does not bring much benefit unless a machine has many CPUs or cores. Note that
if the service instance has more than one core, you may start multiple requests
so that all cores are utilised, however this is optional and not a requirement
of the assignment.

Using a work queue to let instances control the degree of parallelisation is a
common architecture pattern. It is possible to “push” requests to instances but
there must be a mechanism to avoid pushing too many requests to an instance.

The transcoding processes should also log their progress to a log file
(called minimoto.log) in the home directory of the service instance.
The specific log file format is up to you, but it should contain information
about each run of the transcoding process and provide details such as the
success or failure of the run, any arguments received, and any other interesting
output that could help diagnose and fix problems. Note that there should be one
log file per service instance. All transcoding processes running on the same
service instance must write (append) to the same log file.
"""

import os
import boto3

from minimoto_constants import *


def main():
    # Log to minimoto.log
    print("minimoto service starting")
    print("minimoto service finished")

    '''
    aws sqs delete-message --queue-url https://sqs.ap-southeast-2.amazonaws.com/442016026318/minimoto-group-12 --receipt-handle "AQEByQUiYpTQHNjt5oo3keRpJDp49dUZZtSCaHT8jNxk7pT0QuN8H5KgV13lI5ThBs+hcOBVxNj+GNLYJNa1OTr6Id048+l718hM8lCA421hFf8f9aJCNeUl4EkGE++pbAwiuNRyGJBX1P57MoC4q2wfuhHWn6cKSNUtQUy/kPdwKl3LTTnS+Xn2EzWPpN+0gdu/vDy6DKdUiCEwEBsp/nLzj6cHJbTEtq+6ScvJ5Zs/5as70fZiGF2GEF4srHnr8y5HhwwRtKZZcKp+6rYg0yCpWN220oakfqkjiY3vcAdqRMhp1Y/UXl04PajJcl3nBlXB8rYhdiouv+kVCFzkR3e73FXL7qJ68YWtKNmVcns4RpDb03IGV13jaC8y3utDrp6s2OhzwkbPHfaOORclTNTonQ=="

    aws sqs receive-message --queue-url https://sqs.ap-southeast-2.amazonaws.com/442016026318/minimoto-group-12
    '''
    # If the instance is still processing the previous request, do nothing and exit.
    # ?????

    # Pull a request from an SQS queue. If no request is found, do nothing and exit.
    print("Trying to get a request from queue")
    sqs = boto3.resource("sqs", region_name="ap-southeast-2")
    queue = sqs.get_queue_by_name(QueueName=TRANSCODING_REQUESTS_QUEUE_NAME)
    message = queue.receive_messages()

    # Download all images from the S3 bucket specified in the request (e.g., au.edu.unsw.cs9243.input/sample_images_xyz).
    s3 = boto3.resource("s3", region_name="ap-southeast-2")
    input_bucket = s3.Bucket(INPUT_BUCKET_NAME)

    # Convert a series of images to an MP4 video using avconv (it is up to you how you order the images, but ordering based on filename would be sufficient).
    # Upload the MP4 video to the S3 bucket specified in the request (e.g., au.edu.unsw.cs9243.output).
    video_name = ".mp4"
    output_bucket = s3.Bucket(OUTPUT_BUCKET_NAME)
    output_bucket.upload_file(video_name, video_name)
    # Delete request from queue


if __name__ == "__main__":
    main()

