#!/usr/bin/python

import sys
import subprocess

keyfile = sys.argv[1]
aws_access_key_id = sys.argv[2]
aws_secret_access_key = sys.argv[3]

# Set up keys and region
subprocess.run("aws configure set aws_access_key_id %s" % (aws_access_key_id))
subprocess.run("aws configure set aws_secret_access_key %s" % (aws_secret_access_key))
subprocess.run("aws configure set region ap-southeast-2")

# Create SQS queue
queue_name = "something" # TODO choose a better name
subprocess.run(("aws sqs create-queue --queue-name %s" % (queue_name)).split()) # TODO need to see output to get SQS URL

# Create input S3 bucket
subprocess.run("aws s3api create-bucket ")

# Create output S3 bucket


# Print out results


