#!/usr/bin/python3

'''
There are no mandatory output messages. The cleanup program may print out other
messages regarding its progress, it is up to you what those messages are.

The cleanup program must:

- Delete the SQS queue.
- Delete the two S3 buckets.
- Stop and terminate the client instance, the watchdog instance, and all service
instances.
- Delete the service AMI.
- Delete any other resources created by the setup program or by the client,
watchdog, or transcoding service.

Furthermore, the cleanup program must:

- Not delete any resources not created by the setup program or the client,
watchdog or service instances. In particular it must not simply kill all
instances running in the account, or delete all buckets and queues owned
by the account.
- Be able to cleanup after a partially succesfull setup. This means that the
program should be robust in the face of failed commands (e.g. if it attempts
to cleanup a resource that doesn’t exist it should continue on to the next
resource, rather than exit).
'''

import boto3

#- Delete the SQS queue.
#- Delete the two S3 buckets.
#- Stop and terminate the client instance, the watchdog instance, and all service instances.
#- Delete the service AMI.
#- Delete any other resources created by the setup program or by the client, watchdog, or transcoding service.
